# Basic site info
title:                  "Srikanth Kilaru"
tagline:                "Visionary Problem solver"
description:            "Student projects Portfolio site"
keywords:               "Srikanth, Machine Learning, product, engineering, mechatronics, robotics"
show_social_icons:      true # edit file in /_includes/social_links.html
og_locale:              "en_US"

# Site settings & folders
url:                    "https://srikanth-kilaru.github.io"
baseurl:                "/srikanth-kilaru.github.io" 
project_assets:         assets/images/projects

# Site author info
author:
    name:               "Srikanth Kilaru"
    email:              srikilaru@gmail.com
    github_username:    srikanth-kilaru

# Collections info
collections:
    projects:
        output:         true
        permalink:      /projects/:year/:title

# Build settings
source:                 ./
destination:            ./_site
permalink:              /insights/:year/:title
markdown:               kramdown
highlighter:            rouge
timezone:               America/Chicago
exclude:                ["README.md", "LICENSE.md"]

# Site configurations
compress_html:
    clippings:          all
    comments:           ["<!-- ", " -->"]
    endings:            all
    ignore:
        envs:           [local]
    blanklines:         false
    profile:            false
    startings:          [html, head, body]

sass:
    sass_dir:           assets/css/base
    style:              compressed # expanded


plugins_dir:
    - jekyll-sitemap
